### ISSUE TITLE
Wrong host for request access_token

### ISSUE THREAD

**Issue by vladimir-tsapkov** [yandex-money/yandex-money-sdk-nodejs#15]
Hi, you have wrong url for Wallet.getAccessToken method. In yandex-money-sdk/lib/base.js listed two urls: 
Config.MONEY_URL = "https://money.yandex.ru";                                                                                                                                                                                                Config.SP_MONEY_URL = "https://sp-money.yandex.ru";   

So i see that for buildObtainTokenUrl used SP_MONEY_URL, but for getAccessToken the same, so for normal token request you need change it to MONEY_URL in file /yandex-money-sdk/lib/wallet.js line 87.

**Comment by abaranovskii** [comment]
@vladimir-tsapkov 
FYI https://github.com/yandex-money/yandex-money-sdk-nodejs/pull/16

**Comment by abaranovskii** [comment]
@amel-true Could you please merge the fix as this impact on payments.

**Comment by yalovek** [comment]
Thanks, issue resolved in this pr #17
