### ISSUE TITLE
Missing instance_name arg in buildObtainTokenUrl function.

### ISSUE THREAD

**Issue by rmuratov** [yandex-money/yandex-money-sdk-nodejs#7]
API allows to pass `instance_name` but SDK [misses](https://github.com/yandex-money/yandex-money-sdk-nodejs/blob/master/lib/wallet.js#L73) this functionality.

**Comment by yalovek** [comment]
Hi! Fix in this pull request https://github.com/yandex-money/yandex-money-sdk-nodejs/pull/11
